site_name: Blink
site_url: https://1axen.github.io/blink/
repo_url: https://github.com/1Axen/blink
repo_name: 1Axen/blink
theme:
  name: material
  palette:
    primary: indigo
    scheme: slate
  features:
    - content.code.copy
nav:
  - Introduction: 'index.md'
  - "Getting Started":
    - Installation: 'Installation.md'
    - "Creating a New Project": 'New-Description.md'
  - "Language Syntax": "Syntax.md"
  - "Studio Plugin": "Plugin.md"
  - Benchmarks: "Benchmarks.md"
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences