# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
act = "nektos/act@0.2.89"
stylua = "JohnnyMorganz/StyLua@2.5.2"
rojo = "rojo-rbx/rojo@7.7.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
lute = "luau-lang/lute@1.0.0"
