return {
    Keywords = {
        map = true,
        type = true,
        enum = true,
        struct = true,

        event = true,
        ["function"] = true,

        scope = true,
        option = true,
    },

    Primtives = {
        u8 = true,
        u16 = true,
        u32 = true,
        i8 = true,
        i16 = true,
        i32 = true,
        f16 = true,
        f32 = true,
        f64 = true,
        boolean = true,
        string = true,
        vector = true,
        buffer = true,
        Color3 = true,
        CFrame = true,
        Instance = true,
    }
}