name: run-tests

on: [push, pull_request, workflow_dispatch]

jobs:
    run:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Lune
              uses: CompeyDev/setup-lune@v0.1.0

            - name: Run tests
              id: run-tests
              run: |
                  cd test
                  lune run runner

              
