name: run-tests

on: [push, pull_request, workflow_dispatch]

jobs:
    run:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup rokit
              uses: CompeyDev/setup-rokit@v0.1.2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install tooling
              run:
                  rokit install --no-trust-check

            - name: Run tests
              id: run-tests
              run: |
                  cd test
                  lune run runner

              
