name: Styling

on: [push, pull_request, workflow_dispatch]

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        timeout-minutes: 1

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Style
              uses: JohnnyMorganz/stylua-action@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                version: v2.0.2
                args: --check .